name: Docker/Podman CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged=true

    strategy:
        matrix:
          node-version: [14.x, 16.x, 18.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y nodejs npm 

    - name: Check docker and podman
      run: |
        docker --version
        podman --version

    - name: Build npm in docker
      run: |
        cd ./docker
        docker compose up -d --build

        if [ $( docker ps -q | wc -l ) -lt 3 ]
        then
          echo "Test failed, docker not alive"
          exit 1
        fi

        docker ps
        docker container ls
